FROM apache/spark:3.5.1

USER root

RUN apt-get update && apt-get install -y python3-pip && \
    pip3 install --no-cache-dir \
        numpy \
        pandas \
        scikit-learn \
        matplotlib \
        seaborn \
        scipy \
        xgboost \
        statsmodels \
        pyarrow \
        mlflow \
        optuna \
        prophet \ 
        pmdarima && \
    rm -rf /var/lib/apt/lists/*

USER spark